name: Github Pages
env:
  FLUTTER_VERSION: '3.19.6'
on:
  # test
  pull_request:
    types:
      - opened
      - synchronize
#  push:
#    branches: [ main ]

  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
       #  repository名の取得
      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo ::set-output name=repository::$REPOSITORY
       # flutterのインストール
      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
        # flutter check
      - name: Check flutter version
        run: flutter --version
        # パッケージのインストール
      - name: Install packages
        run: flutter pub get
      - name: Build Web
        run: flutter build web --web-renderer html --base-href /${{ steps.version.outputs.repository }}/ --dart-define=GITHUB_TOKEN=${{ secrets.SEARCH_TOKEN }}
        # Deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
