name: Github Pages
env:
  FLUTTER_VERSION: '3.19.6'
on:
  # test
  pull_request:
    types:
      - opened
      - synchronize
#  push:
#    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
        # flutter check
      - name: Check flutter version
        run: flutter --version
        # パッケージのインストール
      - name: Install packages
        run: flutter pub get
        # Deploy
      - name: Deploy
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /gh-pages/
          customArgs: --dart-define="GITHUB_TOKEN=${{ secrets.SEARCH_TOKEN }}"
